name: 'Standardize Repository'
description: 'Sync common files of repos'
inputs:
  repo-type:
    required: true
    description: Repository Type
    default: 'terraform'
  test-action:
    required: true

runs:
  using: composite
  steps:
    - name: Update PR Templates
      shell: bash
      run: | 
        git submodule add https://github.com/tahsib-optimizely/sre-default-github-action.git sre-default
        shopt -s dotglob
        dir=sre-default/repo-types/${{ inputs.repo-type }}
        
        mkdir -p .github/

        prtemplate=$(find ./$dir -type f -iname "pull_request_template*")
        codeowners=$(find ./$dir -type f -iname "CODEOWNERS")

        if test ${prtemplate}; then
            mv -f ${prtemplate} .github/PULL_REQUEST_TEMPLATE
        fi

        if test ${codeowners}; then
            mv -f ${codeowners} .github/CODEOWNERS
        fi

        mv -f ./$dir/*  ./

    - name: Clean Up Submodule
      shell: bash
      run: |
        echo "**** Cleaning up submodules ****"
        git submodule deinit -f -- sre-default    
        git rm --cached sre-default    
        rm -rf .git/modules/sre-default
        rm -f .gitmodules
        rm -rf sre-default
        echo "**** Cleaning Complete! ****"
      
    - name: Push to new-pr-template branch
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: sre metadata updated
        branch: update-sre-default
        create_branch: true
        push_options: --force

    - name: Create PR from new-pr-template branch
      uses: devops-infra/action-pull-request@v0.5.5
      with:
        github_token: ${{ inputs.test-action }}
        source_branch: update-sre-default
        target_branch: main
        title: SRE Metadata Updated

