name: 'SRE Metadata Update'
description: 'Sync common files of a repository'
inputs:
  repository-type:
    required: true
    description: 'Repository Type'
    default: 'terraform'
  pre-commit-config:
    required: true
    description: 'Pre Commit Config'
    default: 'default'
  github-token:
    required: true

runs:
  using: composite
  steps:
    - name: Fetching Updated Common Files
      shell: bash
      run: | 
        git submodule add https://github.com/tahsib-optimizely/sre-metadata-github-action.git sre-metadata
        shopt -s dotglob
        dir=sre-metadata/repository-types/${{ inputs.repository-type }}
        
        mkdir -p .github/

        prTemplate=$(find ./$dir -type f -iname "pull_request_template*")
        codeowners=$(find ./$dir -type f -iname "CODEOWNERS")
        preCommitConfig=$(find ./$dir -type f -iname "*pre-commit-${{ inputs.pre-commit-config }}.yaml")

        if test ${prTemplate}; then
            echo '=====> PULL_REQUEST_TEMPLATE file added !'
            mv -f ${prTemplate} .github/PULL_REQUEST_TEMPLATE
        fi

        if test ${codeowners}; then
            echo '====> CODEOWNERS file added !'
            mv -f ${codeowners} .github/CODEOWNERS
        fi

        if test ${preCommitConfig}; then
            shopt -s dotglob
            echo '====> .pre-commit-config.yaml file added !'
            mv -f ${preCommitConfig} .github/.pre-commit-config.yaml
        fi

        find ./$dir -type f -iname "*pre-commit*" -exec rm {} +
        
        if [ -z "$(ls -A ./$dir)" ]; then
          echo "Nothing else to copy"
        else
          mv -f ./$dir/*  ./
        fi

        

    - name: Clean Up Submodule
      shell: bash
      run: |
        echo "**** Cleaning up submodules ****"
        git submodule deinit -f -- sre-metadata    
        git rm --cached sre-metadata    
        rm -rf .git/modules/sre-metadata
        rm -f .gitmodules
        rm -rf sre-metadata
        echo "**** Cleaning Complete! ****"
      
    - name: Push To sre-metadata-update Branch
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: sre metadata updated
        branch: sre-metadata-update
        create_branch: true
        push_options: --force

    - name: Create PR From sre-metadata-update To main
      uses: devops-infra/action-pull-request@v0.5.5
      with:
        github_token: ${{ inputs.github-token }}
        source_branch: sre-metadata-update
        target_branch: main
        title: SRE Metadata Updated

